### ISSUE TITLE
Сymbals, цимбалы и кимвалы

### ISSUE THREAD

**Issue by SelenIT** [FrontenderMagazine/es6-in-depth-symbols#3]
Инструмент, показанный на картинке в статье — не [цимбалы](https://ru.wikipedia.org/wiki/%D0%A6%D0%B8%D0%BC%D0%B1%D0%B0%D0%BB%D1%8B), а [кимвалы](https://ru.wikipedia.org/wiki/Кимвал). В принципе, не критично, и оба названия созвучны с «символами», но глаз цепляется за неточность(. Плюс с кимвалами лучше «собирается» шутка, которая была после этой картинки в оригинале:)

**Comment by subzey** [comment]
:+1:

**Comment by SilentImp** [comment]
Большинство людей понятия не имеют ни о цимбалах, ни о кимвалах и просто интуитивно ассоциируют это слово с «той штукой» на фотографии, но я, однако, не вижу причин не сделать такое уточнение.
